# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/bmend/Documents/EDESTA/EDESTA.cache/wt [current_project]
set_property parent.project_path C:/Users/bmend/Documents/EDESTA/EDESTA.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib work [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/bmend/Documents/EDESTA/EDESTA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/bmend/OneDrive/Ambiente de Trabalho/faculdade/4ano/2semestre/CR/ForSorting16.coe}}
read_vhdl -library work {
  C:/Users/bmend/Documents/EDESTA/EDESTA.srcs/sources_1/new/segment_decoder.vhd
  C:/Users/bmend/Documents/EDESTA/EDESTA.srcs/sources_1/new/DispCont.vhd
  C:/Users/bmend/Documents/EDESTA/EDESTA.srcs/sources_1/new/BinToBCD16.vhd
  C:/Users/bmend/Documents/EDESTA/EDESTA.srcs/sources_1/new/BCD_disp.vhd
  C:/Users/bmend/Documents/EDESTA/EDESTA.srcs/sources_1/new/FromVector.vhd
  C:/Users/bmend/Documents/EDESTA/EDESTA.srcs/sources_1/new/Unroll_ROM.vhd
  C:/Users/bmend/Documents/EDESTA/EDESTA.srcs/sources_1/new/cnter.vhd
  C:/Users/bmend/Documents/EDESTA/EDESTA.srcs/sources_1/new/TOP.vhd
}
read_ip -quiet C:/Users/bmend/Documents/EDESTA/EDESTA.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/bmend/Documents/EDESTA/EDESTA.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/bmend/OneDrive/Ambiente de Trabalho/faculdade/4ano/2semestre/CR/CrTemp/Nexys4Alunos.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/bmend/OneDrive/Ambiente de Trabalho/faculdade/4ano/2semestre/CR/CrTemp/Nexys4Alunos.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TOP -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
